name              'redisio'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures redis'
version           '7.2.0'
source_url        'https://github.com/sous-chefs/redisio'
issues_url        'https://github.com/sous-chefs/redisio/issues'
chef_version      '>= 16'

suports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'rocky'
supports 'scientific'
supports 'suse'
supports 'ubuntu'

depends 'selinux'
